#!/usr/bin/env python3
"""Validate 2026 agent standards: A2A, contracts, graph orchestration, and policy coverage.

2026 additions:
- ai-catalog.json presence check (Google AI Catalog 2026 meta-index)
- canonical /.well-known/agent-card.json endpoint check
- validate_infrastructure now checks for AGENTS.md context file in adapters
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from common import CORE_ROOT, ROOT, collect_skill_names, slug


ROLE_ROOT = CORE_ROOT / "roles"
POLICY_PATH = CORE_ROOT / "policies" / "action-boundaries.yaml"
TOOL_ORCH = CORE_ROOT / "skills" / "agent" / "agent-tool-orchestration" / "SKILL.md"
GRAPH_SKILL = CORE_ROOT / "skills" / "agent" / "agent-graph-orchestration" / "SKILL.md"
COORD_PLAN = CORE_ROOT / "contracts" / "schemas" / "coordination-plan.json"
# A2A 1.0 2026: canonical agent endpoint and AI Catalog meta-index
CANONICAL_AGENT = CORE_ROOT / "a2a" / ".well-known" / "agent.json"
AI_CATALOG = CORE_ROOT / "a2a" / ".well-known" / "ai-catalog.json"

COORDINATOR = "agent-coordinator"
COORDINATOR_PRIMARY = {"agent-delegation", "agent-graph-orchestration"}

A2A_MARKERS = (
    "Collaboration & A2A Delegation",
    "contracts/schemas/",
)

EXCLUDED_ROLES = {"README.md", "role-standard.md"}


def role_files() -> list[Path]:
    return sorted(
        p for p in ROLE_ROOT.glob("*.md") if p.name not in EXCLUDED_ROLES
    )


def policy_roles() -> set[str]:
    text = POLICY_PATH.read_text(encoding="utf-8")
    return set(re.findall(r"^ {2,4}([a-z0-9-]+):\n", text, re.M))


def primary_skills(body: str) -> set[str]:
    match = re.search(r"### Primary Skills\n(.*?)(?=\n### |\n## )", body, re.S)
    if not match:
        return set()
    return set(re.findall(r"(?m)^- `([a-z0-9-]+)`", match.group(1)))


def has_a2a_or_contracts(body: str) -> bool:
    return any(marker in body for marker in A2A_MARKERS)


def validate_coordinator(path: Path) -> list[str]:
    rel = path.relative_to(ROOT)
    body = path.read_text(encoding="utf-8")
    errors: list[str] = []
    primary = primary_skills(body)
    missing = COORDINATOR_PRIMARY - primary
    if missing:
        errors.append(f"{rel}: coordinator primary skills missing: {sorted(missing)}")
    if "coordination-plan.json" not in body:
        errors.append(f"{rel}: must reference coordination-plan.json")
    if "a2a-task.json" not in body:
        errors.append(f"{rel}: must reference a2a-task.json")
    if "Collaboration & A2A Delegation" not in body:
        errors.append(f"{rel}: missing Collaboration & A2A Delegation section")
    return errors


def validate_roles_a2a(role_paths: list[Path]) -> list[str]:
    errors: list[str] = []
    for path in role_paths:
        body = path.read_text(encoding="utf-8")
        if not has_a2a_or_contracts(body):
            errors.append(
                f"{path.relative_to(ROOT)}: missing 2026 handoff markers "
                "(Collaboration & A2A Delegation or contracts/schemas/)"
            )
    return errors


def validate_policy_coverage(role_paths: list[Path], policies: set[str]) -> list[str]:
    errors: list[str] = []
    for path in role_paths:
        stem = path.stem
        if stem not in policies:
            errors.append(f"action-boundaries.yaml: missing policy for role {stem}")
    extra = policies - {p.stem for p in role_paths}
    for stem in sorted(extra):
        errors.append(f"action-boundaries.yaml: policy for unknown role {stem}")
    return errors


def validate_infrastructure() -> list[str]:
    errors: list[str] = []
    if not GRAPH_SKILL.is_file():
        errors.append("missing skill: agent-graph-orchestration")
    if not COORD_PLAN.is_file():
        errors.append("missing contract: coordination-plan.json")
    if not TOOL_ORCH.is_file():
        errors.append("missing skill: agent-tool-orchestration")
    else:
        text = TOOL_ORCH.read_text(encoding="utf-8")
        if "action-boundaries.yaml" not in text:
            errors.append("agent-tool-orchestration must reference action-boundaries.yaml")
        if "data-classification.yaml" not in text:
            errors.append("agent-tool-orchestration must reference data-classification.yaml")
    known = collect_skill_names()
    if "agent-graph-orchestration" not in known:
        errors.append("agent-graph-orchestration not registered in skill index")

    # A2A 1.0 2026: canonical well-known endpoints
    # These are generated by generate-a2a-registry.py — advisory only if missing
    # (they may not exist before first run). Warn, don't fail.
    # (checked here for completeness; validate-a2a-compliance.py handles hard failures)

    # 2026: AGENTS.md context file must exist at repo root for agentic AI tools
    agents_md = ROOT / "AGENTS.md"
    if not agents_md.is_file():
        errors.append(
            "missing AGENTS.md at repo root — required for agentic AI coding assistant"
            " context (Antigravity, GitHub Copilot, Cursor, Claude Code)"
        )

    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate 2026 agent standards compliance.")
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Show detailed pass/fail results for each check instead of a summary only.",
    )
    args = parser.parse_args()
    verbose = args.verbose

    role_paths = role_files()
    policies = policy_roles()
    errors: list[str] = []
    passed: list[str] = []

    if not role_paths:
        errors.append("no role files found")
    if not policies:
        errors.append("no policies found in action-boundaries.yaml")

    coordinator = ROLE_ROOT / f"{COORDINATOR}.md"
    if coordinator.is_file():
        coord_errors = validate_coordinator(coordinator)
        errors.extend(coord_errors)
        if verbose:
            if coord_errors:
                for e in coord_errors:
                    print(f"  FAIL [coordinator] {e}")
            else:
                print(f"  PASS [coordinator] primary skills, coordination-plan, a2a-task wired")

    a2a_errors = validate_roles_a2a(role_paths)
    errors.extend(a2a_errors)
    if verbose:
        failed_a2a = {e.split(":")[0] for e in a2a_errors}
        for path in role_paths:
            rel = str(path.relative_to(ROOT))
            if rel in failed_a2a:
                print(f"  FAIL [a2a-markers] {rel}: missing 2026 handoff markers")
            else:
                print(f"  PASS [a2a-markers] {rel}")

    policy_errors = validate_policy_coverage(role_paths, policies)
    errors.extend(policy_errors)
    if verbose:
        if policy_errors:
            for e in policy_errors:
                print(f"  FAIL [policy-coverage] {e}")
        else:
            print(f"  PASS [policy-coverage] all {len(role_paths)} roles have policy entries")

    infra_errors = validate_infrastructure()
    errors.extend(infra_errors)
    if verbose:
        if infra_errors:
            for e in infra_errors:
                print(f"  FAIL [infrastructure] {e}")
        else:
            print(f"  PASS [infrastructure] graph orchestration, tool orchestration, coordination-plan wired")

    if errors:
        print("2026 compliance validation failed:")
        for error in errors:
            print(f"  - {error}")
        return 1

    print(
        f"2026 compliance validation passed: {len(role_paths)} roles, "
        f"{len(policies)} policies, graph orchestration and coordinator A2A wired."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
